export default {
    AUTH: 'Auth',
    MAIN: 'Main',
    WALKTHROUGH: 'Walkthrough',
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    RESET_PASSWORD: 'Reset Password',
    HOME: 'Home',
    BOOKING: 'Booking',
    NEWS: 'News',
    ACCOUNT: 'Account',
    POSTS: 'Posts',
    PROFILE_SETTING: 'Profile Setting',
    HOTEL_BLOCK_VIEW: 'Hotel Block View',
};
